const translations = {
    en: {
        name: "Jhayramm Jeevan",
        title: "Software Engineer | 3D Graphics Designer",
        info: "Welcome to my portfolio! I'm Jhayramm Jeevan Simon, an undergraduate software developer at Sunway University. I excel in programming, web development, SQL, and user interface design, with certifications in Ethical Hacking and Network Defense from EC-Council. My experience extends to 3D animation and game development, where I strive to enhance user experiences. Explore my work to see how I use data science, machine learning, and advanced technologies to solve complex problems and create impactful solutions.",
        about: "About",
        contact: "Contact",
        projects: "Projects",
        home: "Home",
        reach: "You can reach me via email at jhayramm05@gmail.com",
    },

    es: {
        name: "Jhayramm Jeevan",
        title: "Ingeniero de Software | Diseñador de Gráficos 3D",
        info: "¡Bienvenido a mi portafolio! Soy Jhayramm Jeevan Simon, desarrollador de software universitario en la Universidad Sunway. Destaco en programación, desarrollo web, SQL y diseño de interfaces de usuario, con certificaciones en Hacking Ético y Defensa de Redes de EC-Council. Mi experiencia abarca la animación 3D y el desarrollo de juegos, donde me esfuerzo por mejorar las experiencias de usuario. Explora mi trabajo para ver cómo utilizo la ciencia de datos, el aprendizaje automático y tecnologías avanzadas para resolver problemas complejos y crear soluciones impactantes.",
        about: "Acerca de",
        contact: "Contacto",
        projects: "Proyectos",
        home: "Inicio",
        reach: "Puedes contactarme por correo electrónico en jhayramm05@gmail.com",
    },
    fr: {
        name: "Jhayramm Jeevan",
        title: "Ingénieur Logiciel | Designer Graphique 3D",
        info: "Bienvenue dans mon portfolio ! Je suis Jhayramm Jeevan Simon, développeur de logiciels en formation à l'Université Sunway. Je suis spécialisé en programmation, développement web, SQL et design d'interfaces utilisateur, avec des certifications en Hacking Éthique et Défense Réseau de EC-Council. Mon expérience inclut l'animation 3D et le développement de jeux, où je m'efforce d'améliorer les expériences utilisateur. Explorez mon travail pour voir comment j'utilise la science des données, l'apprentissage automatique et les technologies avancées pour résoudre des problèmes complexes et créer des solutions impactantes.",
        about: "À propos",
        contact: "Contact",
        projects: "Projets",
        home: "Accueil",
        reach: "Vous pouvez me joindre par email à l'adresse jhayramm05@gmail.com",
    },
    de: {
        name: "Jhayramm Jeevan",
        title: "Softwareingenieur | 3D-Grafikdesigner",
        info: "Willkommen in meinem Portfolio! Ich bin Jhayramm Jeevan Simon, ein angehender Softwareentwickler an der Sunway University. Ich habe mich auf Programmierung, Webentwicklung, SQL und Benutzeroberflächendesign spezialisiert, mit Zertifizierungen in Ethical Hacking und Network Defense von EC-Council. Meine Erfahrung erstreckt sich auf 3D-Animation und Spielentwicklung, wo ich darauf abziele, Benutzererfahrungen zu verbessern. Entdecken Sie meine Arbeit, um zu sehen, wie ich Datenwissenschaft, maschinelles Lernen und fortschrittliche Technologien einsetze, um komplexe Probleme zu lösen und wirkungsvolle Lösungen zu schaffen.",
        about: "Über",
        contact: "Kontakt",
        projects: "Projekte",
        home: "Startseite",
        reach: "Sie können mich per E-Mail unter jhayramm05@gmail.com erreichen",
    },
    zh: {
        name: "Jhayramm Jeevan",
        title: "软件工程师 | 3D图形设计师",
        info: "欢迎来到我的作品集！我是Jhayramm Jeevan Simon，一名在Sunway大学攻读学士学位的软件开发者。我擅长编程、Web开发、SQL和用户界面设计，拥有EC-Council的道德黑客和网络防御认证。我的经验涵盖3D动画和游戏开发，致力于提升用户体验。探索我的工作，看看我如何运用数据科学、机器学习和先进技术解决复杂问题，创造有影响力的解决方案。",
        about: "关于",
        contact: "联系",
        projects: "项目",
        home: "首页",
        reach: "您可以通过电子邮件联系我：jhayramm05@gmail.com",
    },
    ja: {
        name: "Jhayramm Jeevan",
        title: "ソフトウェアエンジニア | 3Dグラフィックデザイナー",
        info: "私のポートフォリオへようこそ！私はJhayramm Jeevan Simon、Sunway大学の学部生ソフトウェア開発者です。私はプログラミング、ウェブ開発、SQL、ユーザーインターフェースデザインに優れ、EC-Councilの倫理的ハッキングとネットワーク防御の認定を持っています。私の経験は3Dアニメーションやゲーム開発にも及び、ユーザーエクスペリエンスの向上を目指しています。私の仕事を探索して、データサイエンス、機械学習、先進技術をどのように活用して複雑な問題を解決し、影響力のあるソリューションを作り出しているかを見てください。",
        about: "約",
        contact: "連絡先",
        projects: "プロジェクト",
        home: "ホーム",
        reach: "メールで連絡できます：jhayramm05@gmail.com",
    },
    ko: {
        name: "Jhayramm Jeevan",
        title: "소프트웨어 엔지니어 | 3D 그래픽 디자이너",
        info: "내 포트폴리오에 오신 것을 환영합니다! 저는 Sunway 대학의 학부 소프트웨어 개발자 지향자인 Jhayramm Jeevan Simon입니다. 저는 프로그래밍, 웹 개발, SQL 및 사용자 인터페이스 디자인에서 뛰어나며, EC-Council의 윤리적 해킹 및 네트워크 방어 자격증을 보유하고 있습니다. 제 경험은 3D 애니메이션과 게임 개발까지 이어지며, 사용자 경험을 향상시키기 위해 노력하고 있습니다. 복잡한 문제를 해결하고 혁신적인 솔루션을 창출하기 위해 데이터 과학, 기계 학습 및 고급 기술을 어떻게 활용하는지 제 작업을 살펴보세요.",
        about: "정보",
        contact: "연락처",
        projects: "프로젝트",
        home: "홈",
        reach: "이메일로 연락할 수 있습니다: jhayramm05@gmail.com",
    },
    it: {
        name: "Jhayramm Jeevan",
        title: "Ingegnere del Software | Designer Grafico 3D",
        info: "Benvenuto nel mio portfolio! Sono Jhayramm Jeevan Simon, uno sviluppatore software universitario presso l'Università Sunway. Eccello nella programmazione, nello sviluppo web, SQL e nel design dell'interfaccia utente, con certificazioni in Ethical Hacking e Network Defense da EC-Council. La mia esperienza si estende alla animazione 3D e allo sviluppo di giochi, dove mi impegno per migliorare le esperienze utente. Esplora il mio lavoro per vedere come uso la scienza dei dati, il machine learning e le tecnologie avanzate per risolvere problemi complessi e creare soluzioni di impatto.",
        about: "Informazioni",
        contact: "Contatto",
        projects: "Progetti",
        home: "Home",
        reach: "Puoi contattarmi via email a jhayramm05@gmail.com",
    },
    pt: {
        name: "Jhayramm Jeevan",
        title: "Engenheiro de Software | Designer Gráfico 3D",
        info: "Bem-vindo ao meu portfólio! Eu sou Jhayramm Jeevan Simon, um desenvolvedor de software graduando na Universidade Sunway. Eu me destaco em programação, desenvolvimento web, SQL e design de interface de usuário, com certificações em Ethical Hacking e Network Defense pela EC-Council. Minha experiência se estende à animação 3D e desenvolvimento de jogos, onde busco melhorar as experiências do usuário. Explore meu trabalho para ver como uso ciência de dados, aprendizado de máquina e tecnologias avançadas para resolver problemas complexos e criar soluções impactantes.",
        about: "Sobre",
        contact: "Contato",
        projects: "Projetos",
        home: "Início",
        reach: "Você pode me contatar por email em jhayramm05@gmail.com",
    },
    ru: {
        name: "Jhayramm Jeevan",
        title: "Программист | 3D Графический Дизайнер",
        info: "Добро пожаловать в мой портфолио! Я - Джейрамм Дживан Саймон, студент-программист в Университете Санвэй. Я специализируюсь на программировании, веб-разработке, SQL и дизайне пользовательских интерфейсов, обладаю сертификатами по Этическому Хакингу и Защите Сети от EC-Council. Мой опыт включает 3D-анимацию и разработку игр, где я стремлюсь улучшать пользовательские впечатления. Исследуйте мои работы, чтобы увидеть, как я использую науку о данных, машинное обучение и передовые технологии для решения сложных задач и создания значимых решений.",
        about: "О",
        contact: "Контакт",
        projects: "Проекты",
        home: "Главная",
        reach: "Вы можете связаться со мной по электронной почте: jhayramm05@gmail.com",
    },
    ar: {
        name: "Jhayramm Jeevan",
        title: "مصمم جرافيك ثلاثي الأبعاد | مطور ألعاب",
        info: "أهلاً بك في ملفي الشخصي! أنا جهيرام جيفان سيمون، مطور برمجيات تحت التدريب في جامعة سانواي. أتقن البرمجة وتطوير الويب وقواعد البيانات SQL وتصميم واجهات المستخدم، مع شهادات في القرصنة الأخلاقية والدفاع عن الشبكات من EC-Council. تمتد خبرتي أيضًا إلى الرسوم المتحركة ثلاثية الأبعاد وتطوير الألعاب، حيث أسعى إلى تحسين تجربة المستخدم. استكشف أعمالي لترى كيف أستخدم علوم البيانات، وتعلم الآلة، والتقنيات المتقدمة لحل المشاكل المعقدة وإيجاد حلول ذات تأثير.",
        about: "عن",
        contact: "اتصال",
        projects: "المشاريع",
        home: "الرئيسية",
        reach: "يمكنك التواصل معي عبر البريد الإلكتروني على jhayramm05@gmail.com",
    },
    hi: {
        name: "Jhayramm Jeevan",
        title: "सॉफ्टवेयर इंजीनियर | 3डी ग्राफिक्स डिजाइनर | गेम डेवलपर",
        info: "मेरे पोर्टफोलियो में आपका स्वागत है! मैं झायरम जीवन साइमन हूँ, सनवे विश्वविद्यालय में सॉफ्टवेयर डेवलपर विद्यार्थी हूँ। मुझे प्रोग्रामिंग, वेब डेवलपमेंट, SQL और उपयोगकर्ता अंतरफलक डिजाइन में उत्कृष्टता है, EC-Council से ईथिकल हैकिंग और नेटवर्क डिफेंस प्रमाण पत्रों के साथ। मेरा अनुभव 3D एनिमेशन और गेम डेवलपमेंट तक फैलता है, जहाँ मैं उपयोगकर्ता अनुभवों को बेहतर बनाने का प्रयास करता हूँ। मेरे काम को अनुसंधान करें ताकि आप देख सकें कि मैं डेटा विज्ञान, मशीन लर्निंग और उन्नत प्रौद्योगिकियों का उपयोग करके जटिल समस्याओं का समाधान कैसे करता हूँ और प्रभावी समाधान बनाता हूँ।",
        about: "के बारे में",
        contact: "संपर्क करें",
        projects: "परियोजनाएं",
        home: "मुखपृष्ठ",
        reach: "आप मुझसे ईमेल द्वारा संपर्क कर सकते हैं: jhayramm05@gmail.com",
    },
    bn: {
        name: "Jhayramm Jeevan",
        title: "সফটওয়্যার ইঞ্জিনিয়ার | 3D গ্রাফিক্স ডিজাইনার",
        info: "আমার পোর্টফোলিওতে আপনাকে স্বাগতম! আমি ঝায়রাম জীবন সাইমন, সানওয়ে বিশ্ববিদ্যালয়ে সফটওয়্যার ডেভেলপার ছাত্র। আমি প্রোগ্রামিং, ওয়েব ডেভেলপমেন্ট, SQL এবং ব্যবহারকারী ইন্টারফেস ডিজাইনে অত্যন্ত দক্ষ, EC-Council হকিং ও নেটওয়ার্ক ডিফেন্স থেকে সার্টিফিকেশন প্রাপ্ত। আমার অভিজ্ঞতা 3D অ্যানিমেশন এবং গেম ডেভেলপমেন্টে পর্যবেক্ষণ করে, যেখানে আমি ব্যবহারকারী অভিজ্ঞতা উন্নত করতে চেষ্টা করি। যে ভাবে আমি ডেটা সাইন্স, মেশিন লার্নিং এবং উন্নত প্রযুক্তি ব্যবহার করে জটিল সমস্যার সমাধান করছি এবং প্রভাবশালী সমাধান তৈরি করছি, তা দেখতে আমার কাজ অনুসন্ধান করুন।",
        about: "সম্পর্কিত",
        contact: "যোগাযোগ",
        projects: "প্রকল্প",
        home: "হোম",
        reach: "আপনি আমাকে ইমেলের মাধ্যমে যোগাযোগ করতে পারেন: jhayramm05@gmail.com",
    },
    pl: {
        name: "Jhayramm Jeevan",
        title: "Inżynier Oprogramowania | Projektant Grafiki 3D",
        info: "Witaj w moim portfolio! Jestem Jhayramm Jeevan Simon, studentem informatyki na Uniwersytecie Sunway. Zajmuję się programowaniem, tworzeniem stron internetowych, SQL oraz projektowaniem interfejsów użytkownika. Mam certyfikaty w dziedzinie Etycznego Hackingu oraz Obrony Sieciowej od EC-Council. Moje doświadczenie obejmuje również animację 3D oraz tworzenie gier, gdzie staram się poprawiać doświadczenia użytkowników. Zapoznaj się z moimi projektami, aby zobaczyć, jak wykorzystuję naukę danych, uczenie maszynowe oraz zaawansowane technologie do rozwiązywania skomplikowanych problemów i tworzenia wpływowych rozwiązań.",
        about: "O",
        contact: "Kontakt",
        projects: "Projekty",
        home: "Strona główna",
        reach: "Możesz skontaktować się ze mną przez e-mail: jhayramm05@gmail.com",

    },
    nl: {
        name: "Jhayramm Jeevan",
        title: "Software Engineer | 3D Grafisch Ontwerper",
        info: "Welkom op mijn portfolio! Ik ben Jhayramm Jeevan Simon, een bachelorstudent softwareontwikkeling aan de Sunway University. Ik ben gespecialiseerd in programmeren, webontwikkeling, SQL en user interface design, met certificeringen in Ethical Hacking en Network Defense van EC-Council. Mijn ervaring strekt zich ook uit tot 3D-animatie en gameontwikkeling, waarbij ik streef naar het verbeteren van gebruikerservaringen. Ontdek mijn werk om te zien hoe ik data science, machine learning en geavanceerde technologieën gebruik om complexe problemen op te lossen en impactvolle oplossingen te creëren.",
        about: "Over",
        contact: "Contact",
        projects: "Projecten",
        home: "Startpagina",
        reach: "Je kunt me bereiken via e-mail op jhayramm05@gmail.com",
    },
    el: {
        name: "Jhayramm Jeevan",
        title: "Μηχανικός Λογισμικού | Σχεδιαστής Γραφικών 3D",
        info: "Καλώς ήρθατε στο βιογραφικό μου! Είμαι ο Jhayramm Jeevan Simon, προπτυχιακός φοιτητής ανάπτυξης λογισμικού στο Πανεπιστήμιο Sunway. Εξαιρώ σε προγραμματισμό, ανάπτυξη ιστοσελίδων, SQL και σχεδίαση διεπαφής χρήστη, με πιστοποιήσεις σε Ηθικό Χάκινγκ και Άμυνα Δικτύου από το EC-Council. Η εμπειρία μου εκτείνεται στην τρισδιάστατη ανιμείσιον και την ανάπτυξη παιχνιδιών, όπου προσπαθώ να βελτιώσω τις εμπειρίες χρήστη. Εξερευνήστε τη δουλειά μου για να δείτε πώς χρησιμοποιώ επιστήμη δεδομένων, μάθηση μηχανής και προηγμένες τεχνολογίες για να λύνω πολύπλοκα προβλήματα και να δημιουργώ αποτελεσματικές λύσεις.",
        about: "Σχετικά",
        contact: "Επαφή",
        projects: "Έργα",
        home: "Αρχική",
        reach: "Μπορείτε να επικοινωνήσετε μαζί μου μέσω email στο jhayramm05@gmail.com",
    },
    sv: {
        name: "Jhayramm Jeevan",
        title: "Mjukvaruingenjör | 3D Grafisk Designer",
        info: "Välkommen till mitt portfolio! Jag är Jhayramm Jeevan Simon, en studerande softwareutvecklare vid Sunway University. Jag är skicklig inom programmering, webbutveckling, SQL och användargränssnittsdesign, med certifieringar inom Etisk Hacking och Nätverksförsvar från EC-Council. Min erfarenhet sträcker sig även till 3D-animation och spelutveckling, där jag strävar efter att förbättra användarupplevelser. Utforska mitt arbete för att se hur jag använder datavetenskap, maskininlärning och avancerade teknologier för att lösa komplexa problem och skapa effektiva lösningar.",
        about: "Om",
        contact: "Kontakt",
        projects: "Projekt",
        home: "Hem",
        reach: "Du kan nå mig via e-post på jhayramm05@gmail.com",
    },
    no: {
        name: "Jhayramm Jeevan",
        title: "Programvareingeniør | 3D Grafisk Designer",
        info: "Velkommen til mitt portefølje! Jeg er Jhayramm Jeevan Simon, en bachelorstudent i programvareutvikling ved Sunway University. Jeg utmerker meg i programmering, webutvikling, SQL og design av brukergrensesnitt, med sertifiseringer i Etisk Hacking og Nettverksforsvar fra EC-Council. Min erfaring omfatter også 3D-animasjon og spillutvikling, der jeg jobber med å forbedre brukeropplevelser. Utforsk arbeidet mitt for å se hvordan jeg bruker datavitenskap, maskinlæring og avanserte teknologier for å løse komplekse problemer og skape effektive løsninger.",
        about: "Om",
        contact: "Kontakt",
        projects: "Prosjekter",
        home: "Hjem",
        reach: "Du kan nå meg via e-post på jhayramm05@gmail.com",
    },
    da: {
        name: "Jhayramm Jeevan",
        title: "Software Engineer | 3D Grafisk Designer",
        info: "Velkommen til min portefølje! Jeg er Jhayramm Jeevan Simon, en bachelorstuderende i softwareudvikling på Sunway University. Jeg excellerer i programmering, webudvikling, SQL og brugergrænsefladedesign, med certificeringer i Etisk Hacking og Netværksforsvar fra EC-Council. Min erfaring omfatter også 3D-animation og spiludvikling, hvor jeg stræber efter at forbedre brugeroplevelser. Udforsk mit arbejde for at se, hvordan jeg bruger datalogi, maskinlæring og avancerede teknologier til at løse komplekse problemer og skabe effektive løsninger.",
        about: "Om",
        contact: "Kontakt",
        projects: "Projekter",
        home: "Hjem",
        reach: "Du kan kontakte mig via e-mail på jhayramm05@gmail.com",
    }
}
